# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "About-founders-vision"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  enable: true
  image: "/images/about-founders-vision.png"
  image_description: ''
  title: The Founders Vision
  text: |-
    Since 2010, the vision of Oasis Clinics has been to provide the best clinical outcomes and patient education for the community, not only in the treatment of disease but also in prevention.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
