# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Colorful-boxes"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
    enable: true
    light_green_dark_card:
      heading: Our Clinics
      text: Outpatient consultations in over 30 specializations, working together as
        one unit and with patient records
      button: More Info
      button_url: "/clinics"
    light_green_light:
      heading: Specialized Services
      text: Inpatient complimentary services include surgical center, endoscopy, ultrasound,
        and more. Servicing clinics and also available standalone to outside consultants
      button: More Info
      button_url: "/services"
    dark_green_light_card:
      heading: Online Consultations
      text: Online consultations are available in most of Oasis’ outpatient specializations,
        with our top doctors
      button: Request Now
      button_url: "/doctors"
    dark_green_dark:
      heading: New Services
      text: Oasis Clinics also arranges for home visits, including checkups and investigations
        with portable medical devices
      button: Request Now
      button_url: "/new-services"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
