# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Colorful-boxes"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
    enable: true
    light_green_dark_card:
      heading: Hard Drive Data Recovery
      text: >-
        BounceBack Data Recovery provides expert, nondestructive hard drive recovery with advanced tools and 15 years’ experience, offering free estimates, no-recovery-no-fee guarantee, cleanroom repairs, and secure data transfer.
      button: More Info
      button_url: /data-recovery-services/hard-drive-data-recovery/
    light_green_light:
      heading: Server Data Recovery
      text: >-
        BounceBack Data Recovery specializes in server recovery, including RAID, SAN/NAS, and Apple XServe systems. With expert technicians, proprietary tools, and remote support, they minimize downtime and restore critical business data efficiently.
      button: More Info
      button_url: /data-recovery-services/server-raid-data-recovery/
    dark_green_light_card:
      heading: Medical Data Recovery
      text: >-
        BounceBack Data Recovery provides secure, HIPAA-compliant medical data recovery for patient, billing, and imaging records, with strict security protocols, encrypted recovery, business associate agreements, and guaranteed data restoration.
      button: More Info
      button_url: /data-recovery-services/medical-data-recovery/
    dark_green_dark:
      heading: Cell Phone Data Recovery
      text: >-
        BounceBack Data Recovery restores lost cell phone data—including texts, photos, and call logs—across devices and memory cards, offering free evaluations, customized recovery methods, secure handling, and pricing typically between $700–$1200.
      button: More Info
      button_url: /data-recovery-services/cell-phone-data-recovery/
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
