# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Home-hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
hero:
  enable: true
  slide_items:
  - heading: Sheikh Zayed Branch
    schedule: Sat to Thu (09:00 am - 10:00 pm)
    button: Call Now
    button_url: "+20237942522"
  - heading: New Cairo Branch
    schedule: Sat to Thu (09:00 am - 10:00 pm)
    button: Call Now
    button_url: "+201225044544 "
  - heading: North Coast Branch
    schedule: June, July, August & September Everyday from 10:00 am to 12:00 am
    button: Call Now
    button_url: "+201225044544"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
