# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Home-hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
hero:
    enable: true
    slide_items:
      - heading: Data Recovery
        schedule: Secure, confidential, and reliable data restoration
        button: Call Now
        button_url: "3146903009"
      - heading: Data Security
        schedule: Keeping your data safe, private, and fully protected
        button: Call Now
        button_url: "16363330030"
      - heading: DIgital Forensics
        schedule: Certified forensic analysis you can rely on
        button: Call Now
        button_url: "3146903009"
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
