# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Home-about"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
    enable: true
    heading: Why Choose Us?
    image: /images/home/bounceback-why-choose-us.jpg
    image_description: "a person is looking at microscope"
    title: ""
    text: >-
      This is a small company, run by one person who has been in the industry since 2000.  Transparent and honest service is, unfortunately, a rare commodity in this industry.  The goal of BounceBack is to trump the competition from the strategic position of this moral high ground, while offering the best work and service possible with every customer.
    button: Read More
    button_url: /why-choose-us/

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
