# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Home-clinics"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
    enable: true
    heading: Our Clinics
    text: Oasis Clinics is a medical group practice specializing in outpatient and inpatient
      daycare health services. It is a one-of-a-kind polyclinic wholly devoted to outpatient
      services, GIT, endoscopies and inpatient surgical procedures.
    button: Show All
    button_url: "/clinics"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
