# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Home-about"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  enable: true
  heading: Who We Are
  image: "/images/home-about.png"
  image_description: ''
  title: About Oasis Clinics
  text: Oasis Clinics is a medical group practice specializing in outpatient and inpatient
    daycare health services. It is a one-of-a-kind polyclinic wholly devoted to outpatient
    services, GIT, endoscopies and inpatient surgical procedures. Oasis Clinics provides
    a range of integrated medical services designed to provide holistic treatment
    for the whole family in a positive and comfortable environment that adheres to
    the universal infection control standards. With over 30 specialties in one state-of-the-art,
    easy to reach location, Oasis Clinics is the premier supplier of quality medicine
    in the Cairo West suburbs of Sheikh Zayed, Sixth of October, the North Coast (Diplo),
    New Maadi, and New Cairo.
  button: Read More
  button_url: "/about"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
