# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Home-about"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
    enable: true
    heading: BounceBack Data Recovery
    image: /images/home/bounceback-data-recovery-home.jpg
    image_description: "motherboard"
    title:
    text: >-
      BounceBack Data Recovery specializes in salvaging lost, damaged, or otherwise compromised data from all different types of electronic media storage devices. We strive to offer competitive pricing, quick turnaround, and professional and friendly customer service. Our price quotes are firm and all-inclusive… you will never be charged more than the agreed upon quote. And if we don’t recover your data, you don’t pay.
    button: Read More
    button_url: /data-recovery-services/

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
