# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Meet-doctors"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
    enable: true
    heading: MEET OUR DOCTORS
    button: Show All
    button_url: "/doctors"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
