# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Home-services"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
    enable: true
    heading: What clients say about us
    image: /images/google review.webp
    slider:
      - cards:
          - image: /images/susan.png
            image_description: "google-review-susanTaylor"
            name: Susan Taylor-Alonsos
            text: >-
              Not only was Mike able to recover my data, but he was able to repair my MacBook Pro. The hard drive went bad due to planned obsolescence. Apple wanted me to either replace the entire board and strip my data. This service was definitely worth the wait!!! Definitely recommend!
            button_label: See on Gooogle Review
            button_link: https://maps.app.goo.gl/cNsqnFU5ZSWvVEuX7
      - cards:
          - image: /images/carrie-west.png
            image_description: "carrie-west"
            name: Carrie West
            text: >-
              Incredibly fast service! Mike was very helpful and communicative. I could have shopped around for a lower price, but I wanted to make sure my data could be recovered and that the device wouldn't be destroyed in the process. Everything was recovered with no damage to the device, and I'm truly grateful.
            button_label: See on Gooogle Review
            button_link: https://maps.app.goo.gl/Gx8FubN2S1nMKfmx6
      - cards:
          - image: /images/Moom Moomoo.png
            image_description: "Moom Moomo"
            name: Moom Moomo
            text: >-
              This is the best place for data recovery. Its extremely affordable, too, which is a huge plus. That's one thing that scares people off when they're hard drive is shot, the cost... Not with BounceBack. Easily 5 stars.
            button_label: See on Gooogle Review
            button_link: https://maps.app.goo.gl/RynefsZ32xCYeMBaA

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
